# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7eb7d2141315d16558f7a81e2ec39c0c20f64829d3f6f738fafd004735ef5f141aee1ae32bf447f3188d32032d3aa399bcfe16711faa2437bfebf047bfaf9c09

test:
  secret_key_base: 0ca65ab0a297fb7864962e5510a8ef0c57fee6ce55a90f3b63b701aac46a55d6cff746e85a2b213252fb481f98b3ed636c966e529226af2d515cf93108f6e279

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
